using System.Collections.Generic;
using UnityEngine;

public class NameGenerator {

    public static string GenerateNewName(int _rarity, string _baseName)
    {
        List<string> prefixList = PreparePrefixList();
        List<string> suffixList = PrepareSuffixList();

        string prefix = "";
        string suffix = "";

        if (_rarity >= 5)
            prefix += prefixList[Random.Range(0, prefixList.Count - 1)] + " ";
        if (_rarity >= 4)
            suffix += " " + suffixList[Random.Range(0, suffixList.Count - 1)] + " &";
        if (_rarity >= 3)
            prefix += prefixList[Random.Range(0, prefixList.Count - 1)] + " ";
        if (_rarity >= 2)
            suffix += " " + suffixList[Random.Range(0, suffixList.Count - 1)];

        return prefix + _baseName + suffix;
    }

    private static List<string> PreparePrefixList()
    {
        List<string> prefixList = new List<string>
        {
            "Super",
            "Mega",
            "Supra",
            "Cool",
            "Elegant",
            "Classic",
            "Strong",
            "Weird",
            "Strange",
            "Visionary",
            "Massive",
            "Cruel",
            "Savage",
            "Master's",
            "Lunar",
            "Celestial",
            "Pure",
            "Divine",
            "Sacred",
            "Glorious",
            "Victorious",
            "Acclaimed",
            "Admired",
            "Almighty",
            "Anticipated",
            "Arching",
            "Assured",
            "Astonishing",
            "Avoiding",
            "Blocking",
            "Bold",
            "Brawling",
            "Brawny",
            "Brilliant",
            "Brute",
            "Burly",
            "Butchering",
            "Calloused",
            "Celebrated",
            "Clandestine",
            "Combating",
            "Conflicting",
            "Conserving",
            "Constant",
            "Cunning",
            "Curious",
            "Daring",
            "Darting",
            "Dashing",
            "Defensive",
            "Defiant",
            "Deflecting",
            "Demolishing",
            "Dense",
            "Devastating",
            "Dignified",
            "Distinct",
            "Distinguished",
            "Diverting",
            "Divine",
            "Driving",
            "Earthen",
            "Eccentric",
            "Elevated",
            "Elite",
            "Elusive",
            "Enforced",
            "Eradicating",
            "Essential",
            "Esteemed",
            "Exalted",
            "Exceptional",
            "Excessive",
            "Fabled",
            "Fantastic",
            "Fighting",
            "Firm",
            "Flourishing",
            "Foretold",
            "Forgotten",
            "Formidable",
            "Girded",
            "Gleaming",
            "Gliding",
            "Glimmering",
            "Goring",
            "Grounded",
            "Hallowed",
            "Harsh",
            "Hefty",
            "Hulking",
            "Husky",
            "Illustrious",
            "Immaculate",
            "Immense",
            "Impeding",
            "Impressive",
            "Incomparable",
            "Incredible",
            "Informal",
            "Infused",
            "Inspired",
            "Intact",
            "Intense",
            "Launching",
            "Legendary",
            "Loyal",
            "Lurid",
            "Majestic",
            "Marvelous",
            "Merciless",
            "Meticulous",
            "Miraculous",
            "Momentous",
            "Mystic",
            "Negating",
            "Neutralizing",
            "Noble",
            "Notable",
            "Notorious",
            "Novel",
            "Obedient",
            "Obscure",
            "Obstructing",
            "Optimistic",
            "Organic",
            "Outlandish",
            "Outrageous",
            "Palpable",
            "Peerless",
            "Persevering",
            "Praised",
            "Predestined",
            "Preeminent",
            "Prevailing",
            "Pristine",
            "Prized",
            "Propelling",
            "Protective",
            "Pummeling",
            "Radiant",
            "Ravaging",
            "Recoiling",
            "Refined",
            "Relentless",
            "Reliant",
            "Remarkable",
            "Renowned",
            "Repellant",
            "Resilient",
            "Resistant",
            "Respected",
            "Retreating",
            "Revered",
            "Rough",
            "Rugged",
            "Rushing",
            "Ruthless",
            "Sabotaging",
            "Sacred",
            "Scuffling",
            "Secret",
            "Skirmishing",
            "Soaring",
            "Solemn",
            "Solid",
            "Spectacular",
            "Splendid",
            "Splendorous",
            "Stately",
            "Staunch",
            "Steadfast",
            "Stern",
            "Strategic",
            "Stringent",
            "Stupendous",
            "Sublime",
            "Superior",
            "Superlative",
            "Supreme",
            "Sustained",
            "Tactile",
            "Talismanic",
            "Tenacious",
            "Terranean",
            "Terrestrial",
            "Thwarting",
            "Treasured",
            "Trusted",
            "Uncommon",
            "Uncompromising",
            "Unequivocal",
            "Unfathomable",
            "Unparalleled",
            "Unsurpassed",
            "Unwavering",
            "Unwearied",
            "Unyielding",
            "Utmost",
            "Valued",
            "Vengeful",
            "Warring",
            "Wiley"
        };

        return prefixList;
    }

    private static List<string> PrepareSuffixList()
    {
        List<string> suffixList = new List<string>
        {
            "Made by Gods",
            "of Gold",
            "Cheated",
            "of Fire",
            "of Abundance",
            "of Acceleration",
            "of Accuracy",
            "of Adversaries",
            "of Afar",
            "of Affluence",
            "of Aggression",
            "of Agility",
            "of Agony",
            "of Ailment",
            "of Animation",
            "of Antagonism",
            "of Aptitude",
            "of Ash",
            "of Aspiration",
            "of Attainment",
            "of Awareness",
            "of Beyond",
            "of Blistering",
            "of Blizzards",
            "of Boundlessness",
            "of Bounty",
            "of Breadth",
            "of Briars",
            "of Burning",
            "of Calculation",
            "of Carnage",
            "of Carving",
            "of Cautery",
            "of Certainty",
            "of Chilling",
            "of Cinders",
            "of Clashing",
            "of Claws",
            "of Coals",
            "of Coldness",
            "of Colossus",
            "of Confidence",
            "of Consumption",
            "of Contempt",
            "of Contention",
            "of Conviction",
            "of Courage",
            "of Craft",
            "of Creation",
            "of Currents",
            "of Cyclones",
            "of Dawn",
            "of Daylight",
            "of Deception",
            "of Defiance",
            "of Design",
            "of Detail",
            "of Diligence",
            "of Discord",
            "of Disease",
            "of Disparity",
            "of Dispute",
            "of Dissension",
            "of Distance",
            "of Dread",
            "of Dusk",
            "of Embers",
            "of Emphasis",
            "of Endeavor",
            "of Endowment",
            "of Energy",
            "of Enhancement",
            "of Enormity",
            "of Epidemic",
            "of Equity",
            "of Exactness",
            "of Excellence",
            "of Excess",
            "of Exchange",
            "of Exhilaration",
            "of Expanse",
            "of Extension",
            "of Faith",
            "of Fangs",
            "of Fire",
            "of Flame",
            "of Focus",
            "of Foes",
            "of Foresight",
            "of Fortitude",
            "of Freezing",
            "of Frigidity",
            "of Frostbite",
            "of Glaciers",
            "of Glory",
            "of Grandeur",
            "of Greatness",
            "of Greed",
            "of Hail",
            "of Hardiness",
            "of Haste",
            "of Honor",
            "of Hope",
            "of Horizon",
            "of Hostility",
            "of Hurricanes",
            "of Ice",
            "of Icebergs",
            "of Ignition",
            "of Illness",
            "of Impalement",
            "of Impulse",
            "of Independence",
            "of Infection",
            "of Infirmity",
            "of Influence",
            "of Ingenuity",
            "of Insight",
            "of Intellect",
            "of Intent",
            "of Invigoration",
            "of Joviality",
            "of Judgment",
            "of Knowledge",
            "of Laceration",
            "of Lechery",
            "of Length",
            "of Lightning",
            "of Liveliness",
            "of Magnitude",
            "of Malady",
            "of Malevolence",
            "of Measure",
            "of Midnight",
            "of Might",
            "of Momentum",
            "of Monstrosity",
            "of Mortality",
            "of Numbness",
            "of Objection",
            "of Old",
            "of Omniscience",
            "of Opposition",
            "of Patience",
            "of Perfection",
            "of Perforation",
            "of Perjury",
            "of Pestilence",
            "of Precision",
            "of Premeditation",
            "of Pretense",
            "of Privilege",
            "of Projection",
            "of Prominence",
            "of Promise",
            "of Prosperity",
            "of Protest",
            "of Puncture",
            "of Purpose",
            "of Reach",
            "of Reclamation",
            "of Recovery",
            "of Recuperation",
            "of Refreshment",
            "of Refuge",
            "of Regard",
            "of Reinvention",
            "of Rejoicing",
            "of Rejuvenation",
            "of Reliance",
            "of Remoteness",
            "of Renewal",
            "of Repression",
            "of Reprieval",
            "of Resolution",
            "of Resolve",
            "of Restoration",
            "of Retaliation",
            "of Retribution",
            "of Revendication",
            "of Revenge",
            "of Reversal",
            "of Revival",
            "of Risk",
            "of Rivalry",
            "of Robustness",
            "of Scorching",
            "of Score",
            "of Searing",
            "of Seasons",
            "of Secrecy",
            "of Shadows",
            "of Sharpness",
            "of Shivering",
            "of Sickness",
            "of Singeing",
            "of Sleet",
            "of Slicing",
            "of Slush",
            "of Smoke",
            "of Snowflakes",
            "of Snowstorms",
            "of Sorrows",
            "of Span",
            "of Spikes",
            "of Stabbing",
            "of Stability",
            "of Starlight",
            "of Stretch",
            "of Stride",
            "of Strife",
            "of Strike",
            "of Struggle",
            "of Sturdiness",
            "of Sunrise",
            "of Sunset",
            "of Surplus",
            "of Survival",
            "of Symptoms",
            "of Talent",
            "of Talons",
            "of Target",
            "of Teeth",
            "of Tempests",
            "of the Badger",
            "of the Banished",
            "of the Bear",
            "of the Boar",
            "of the Deft",
            "of the Destructive",
            "of the Dexterous",
            "of the Dog",
            "of the Dove",
            "of the Eagle",
            "of the Effortless",
            "of the Falcon",
            "of the Feral",
            "of the Forgiven",
            "of the Fox",
            "of the Gull",
            "of the Haughty",
            "of the Hawk",
            "of the Heron",
            "of the Honed",
            "of the Hunter",
            "of the Jarred",
            "of the Jolted",
            "of the Leopard",
            "of the Lion",
            "of the Looter",
            "of the Nimble",
            "of the Oppressive",
            "of the Owl",
            "of the Panther",
            "of the Parasite",
            "of the Pillager",
            "of the Plunderer",
            "of the Predator",
            "of the Proud",
            "of the Provoked",
            "of the Rabid",
            "of the Raider",
            "of the Ram",
            "of the Raven",
            "of the Redeemed",
            "of the Savage",
            "of the Serpent",
            "of the Shaken",
            "of the Shocked",
            "of the Slayer",
            "of the Sparrow",
            "of the Speedy",
            "of the Spry",
            "of the Startled",
            "of the Swift",
            "of the Thief",
            "of the Unbridled",
            "of the Untamed",
            "of the Venomous",
            "of the Wild",
            "of the Wolf",
            "of the Zapped",
            "of Thorns",
            "of Threat",
            "of Thunder",
            "of Torment",
            "of Transcendence",
            "of Transience",
            "of Truth",
            "of Tusks",
            "of Twilight",
            "of Urgency",
            "of Valor",
            "of Vastness",
            "of Velocity",
            "of Vengeance",
            "of Vibrancy",
            "of Vigilance",
            "of Vindication",
            "of Virtue",
            "of Virulence",
            "of Vitality",
            "of Wealth",
            "of Winter",
            "of Wisdom",
            "of Wounding",
            "of Youth",
            "of Marc",
            "of 42"
        };

        return suffixList;
    }
}
